name: SonarQube PR Analysis

on:
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  sonarqube:
    name: SonarQube PR Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip
          sudo mv sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner
          echo 'export PATH=$PATH:/opt/sonar-scanner/bin' >> $GITHUB_ENV
          
      - name: Run SonarScanner
        run: sonar-scanner -Dsonar.projectKey=SonarPR -Dsonar.host.url=http://localhost:9000 -Dsonar.login=${{ secrets.SONAR_TOKEN }}
